Fix missing return statement
In function `bool stream::for_each(std::istream&, std::function<void(T&)>&)`, and
In function `bool stream::for_each_parallel(std::istream&, std::function<void(T&)>&)`:
error: no return statement in function returning non-void [-Werror=return-type]